### ISSUE TITLE
"Add Comments" does not have a corresponding configuration

### ISSUE THREAD

**Issue by dougcunha** [jcraane/gpt-mentor-plugin#14]
The command "Add Comments" does not have a corresponding configuration. The configuration that most closely resembles it is "Add Docs"; however, this configuration does not affect the outcome of "Add Comments," as demonstrated below.

![image](https://user-images.githubusercontent.com/744700/229146160-b0dda146-a713-4222-ab0c-437436605165.png)
![image](https://user-images.githubusercontent.com/744700/229146232-884ff11e-a5ce-45f8-819e-1389ee12bf8a.png)
![image](https://user-images.githubusercontent.com/744700/229146954-0d850c38-e9a6-4e56-ba8b-2a689269bc79.png)

**Comment by dougcunha** [comment]
As a side note, it would be perfect if the captions of the commands on the menu matched those in the configuration.

Anyway, thank you for this great tool.

**Comment by jcraane** [comment]
This should be fixed in the upcoming 0.0.7 release. If this is not the case please let me know. Expect the release within a couple of days from now.
