### ISSUE TITLE
Default prompts require a new line before adding user question

### ISSUE THREAD

**Issue by PSF1** [jcraane/gpt-mentor-plugin#9]
Reviewing chat history I see that the plugin sends the settled prompts without a new line before concatenating the user prompt:

![imagen](https://user-images.githubusercontent.com/10193279/228512720-51e4e428-6cdc-4b49-9c40-8da80e3e78fa.png)

I think that we'll get betters prompts with the new line.

**Comment by jcraane** [comment]
This one should be fixed in version 0.0.5 (which is available for download). If you still experience issues with this let me know!
